cli/cmd/build/build.go
cli/cmd/build/options.go
cli/cmd/pull/options.go
cli/cmd/pull/pull.go
cli/cmd/push/push.go

This PR adds the output format flags to the pull cli command and changes the `fmt.Fprint()` calls to `cmd.Print` calls.

refactor: small fixes on cli

---

.github/workflows/demo-local.yaml
.github/workflows/reusable-dir-demo.yaml
install/charts/dir/apiserver/values.yaml
install/charts/dir/values.yaml

* Fix zot service name in helm values
* Add demo workflow that runs agent directory build/push/publish/pull commands with one dir server node
* Example run https://github.com/paralta/dir/actions/runs/14226199344/job/39866198246

ci: add local demo workflow 

---

Taskfile.yml

Keep getting the following error when running `task server:start`
```
Error: statfs /tmp/config.json: no such file or directory
```

fix: rename zot-config.json to config.json

---

USAGE.md
cli/build.config.yml
cli/builder/config/config.go
cli/cmd/build/build.go
e2e/testdata/build.config.yml

* Add option to enable or disable oasf validation during build
Currently, compliance with OASF skills is mandatory, but this new option will accommodate DIR adopters who may not wish to adhere to these requirements.

feat: add option to enable or disable oasf validation

---

.github/workflows/demo-local-windows.yaml
Taskfile.yml

* Compile windows-amd64 binary
* Add CI workflow to compile the CLI, build an agent, and verify the binary on Windows (example run: https://github.com/paralta/dir/actions/runs/14405424553/job/40400673832)

feat: windows binary

---

server/routing/internal/p2p/server_test.go

This PR temporarily turns off a unit test that is flaky and causes problem in the CI.

fix: flaky e2e test

---

.github/workflows/reusable-test-e2e.yaml
.github/workflows/reusable-test.yaml
Taskfile.yml
e2e/client_test.go
e2e/config/config.go
e2e/dirctl_network_cmd_test.go
e2e/dirctl_network_deploy_test.go
e2e/dirctl_test.go
e2e/go.mod
e2e/suite_test.go
server/routing/handler.go
server/routing/handler_test.go
server/routing/routing_local.go
server/routing/routing_remote.go
server/routing/rpc/rpc.go
server/routing/test_utils.go

Check https://github.com/agntcy/dir/actions/runs/14832685915/job/41637153235#step:12:15 for logs showing the issues described below
* When an agent was pushed and published on Peer 1, the output of `dirctl list "/skills/Natural Language Processing" --server-addr peer1 --network` was empty. This was happening because we skipped running list on self, thus no agent was found. Please check https://github.com/agntcy/dir/commit/c11a1da5bfbf5ac8320ce9b3a83b57149e394a8f for the fix.
* On a network with a bootstrap node and 3 other nodes, when an agent was pushed and published on Peer 1, the output of `dirctl list "/skills/Natural Language Processing" --server-addr peer2 --network` was 4 agents each on a different node. This happened because all "searched" peers are connected to the peer that …

fix: list command outputs with network flag

---

cli/Dockerfile
server/Dockerfile

This PR removes the `alpine` runner image from the `cli` and `server` dockerfiles and substitutes it with a `distroless` image.

refactor: distroless docker images

---

Taskfile.yml
server/routing/routing_local_test.go

This PR adds benchmark tests to the local router component.
The next step is that based on these benchmark tests we switch out the underlying DBs to something more performant.

test: routing local benchmark

---

tools/python/client/example.py

This PR fixes a bug where the python client converted the uint64 values to string before pushing to the server which later caused errors.
There is sadly no way to easily fix this without us implementing a function that converts strings to ints: https://github.com/protocolbuffers/protobuf/issues/2954

fix: python sdk

---

cli/cmd/hub/hub.go
cli/cmd/push/push.go
hub/hub.go

The `hub` subcommands of `dirctl` returned with exit code 0 on error, now errors are propagated so cobra can exit with status code 1 in this case.

fix: cli hub subcommand to exit with 1 on fatal error

---

USAGE.md
server/controller/routing.go
server/controller/store.go
server/routing/routing.go
server/routing/routing_local.go
server/routing/routing_local_test.go
server/routing/routing_remote.go
server/routing/rpc/rpc.go
server/store/localfs/localfs.go
server/store/oci/oci.go
server/store/oci/oci_test.go
server/store/store.go
server/types/store.go

Replace all `fmt.Errorf` errors returned from your store and routing methods with `status.Errorf` and appropriate `codes` from http://google.golang.org/grpc/status and https://pkg.go.dev/google.golang.org/grpc/codes, respectively.
**Error Message Example 1**
old
```sh
Error: failed to pull data: failed to receive object: rpc error: code = Unknown desc = failed to lookup: digest does not exist
```
new
```sh
Error: failed to pull data: failed to receive object: rpc error: code = NotFound desc = failed to lookup object: object not found: sha256:1beb8653b5bf888274c1e2c3754e096b0242ceee8518c330be3239fa88a4fc80
```
**Error Message Example 2**
old
```sh
Error: failed to pull data: failed to receive object: rpc error: code = Unknown desc = failed to lookup: failed to check if object exists: …
```

feat: improve grpc error handling

---

hub/auth/login.go
hub/cmd/logout/logout.go
hub/cmd/orgs/orgs.go
hub/cmd/orgswitch/switch.go
hub/cmd/pull/pull.go
hub/cmd/push/push.go

* Fix segfault when running the hub command to list orgs when user is not logged in.
* Plus, add login checks wherever required
Kudos to @jubarbot-cisco for finding this bug 🚀

fix: add login check to avoid segfault

---

cli/cmd/search/search.go
e2e/dirctl_test.go
server/search/sqlite/record.go

CLI fix to print every CID on a new line.
Fixes a bug where the same record returned multiple times because of JOINs.

fix: local search

---

hub/config/config.go
hub/config/constants.go

The new official location of the directory is
https://hub.agntcy.org/directory.
Old dirctl client will still work for some time because, at the moment, there is a 302 temporary HTTP redirection from https://hub.agntcy.org to https://hub.agntcy.org/directory.

feat: new hub https://hub.agntcy.org/directory

---

.github/workflows/ci.yaml

Excludes `api/proto/buf.lock` from the git status check in the `verify-gen` CI job to prevent failures when this file is automatically generated during task gen. 
This issue could cause CI failures in release or main branch runs if OASF code was released after the last commit was merged.

fix: update CI task gen to ignore buf lock file changes

---

.github/workflows/demo-local-windows.yaml
.github/workflows/demo.yaml
README.md
cli/cmd/root.go

This PR removes the deprecated builder functionality and updates the demo workflows to support building from any git reference instead of fixed release versions.
* Remove obsolete builder test data files (agent.base.json, build.config.yml, pyproject.toml)
* Remove `build` command references from CLI and documentation
* Replace demo workflow `version` inputs with `git-ref` parameter for branch/tag/commit builds
* Update signing workflows
https://github.com/agntcy/dir/actions/runs/17240310110 Successful run ✅

refactor: remove builder artifacts and build cmd usages

---

.licensei.toml
cli/go.mod
cli/go.sum
client/go.mod
client/go.sum
client/verify.go
e2e/dirctl_network_sync_test.go
e2e/go.mod
e2e/go.sum
e2e/utils/cli.go

This pull request implements a fallback mechanism that enables client-side signature verification when server-side verification fails, improving system resilience and availability.
* Fallback Verification Logic: Enhanced the Verify method to automatically fallback to client-side cryptographic verification using Cosign when server verification is unsuccessful
* OCI Referrer Integration: Added methods to retrieve signature and public key data from OCI referrers, enabling independent verification without server dependency

feat: fallback to client-side verification

---

hub/auth/apikey.go
hub/auth/login.go
hub/auth/utils/utils.go
hub/cmd/apikey/create/create.go
hub/cmd/info/org/org.go
hub/cmd/pull/pull.go
hub/cmd/push/push.go
hub/service/apikey.go
hub/sessionstore/type.go
hub/utils/auth/auth.go

This PR improves the authentication mechanism for dirctl hub commands by adding support for API key authentication through a file-based approach
- Added a new `--apikey-file` option to multiple commands, allowing users to provide API key credentials in a JSON file
- The API key file follows the format: `{"client_id": "...", "secret": "..."}`
- Implemented in:
- `hub pull` command
- `hub push` command
- Enhanced the authentication logic to follow a clear priority order:
1. API key from file (if provided via `--apikey-file`)
2. API key from environment variables (DIRCTL_CLIENT_ID, DIRCTL_CLIENT_SECRET)
3. Existing session from context (session file created via 'dirctl hub login')
- Removed command line options for directly providing client ID and secret in the `pull` and `push` commands
- …

feat(hub): add support for hub auth via apikey file

---

.github/workflows/brew-formula-update.yaml
HomebrewFormula/README.md

The homebrew binary beyond the 4.6.3 version break the local file installation which our CI relies on for testing the updated formulae. This fix is creating a new local tap for testing and copy the formula from the repository into it

ci(homebrew): use local tap for testing homebrew formulae

---

client/verify.go
e2e/network/02_sync_test.go
server/store/oci/referrers.go
utils/cosign/sign.go

This PR updates the signature attachment method to leverage the OCI 1.1 specification's referrers API to fix https://github.com/agntcy/dir/issues/459.
* **Signature attachment method:** Switched from `ociremote.WriteSignatures()` to [`ociremote.WriteSignaturesExperimentalOCI()`](https://github.com/sigstore/cosign/blob/main/pkg/oci/remote/write.go#L140) in cosign utils to use OCI 1.1 behavior for signature referrers
* **Signature discovery:** Updated signature pulling logic to use OCI referrers API instead of cosign tag-based discovery (`sha256-abc123.sig` format)
* **Test coverage:** Extended E2E tests to include signature verification after sync operations for both full sync and sync by CID

fix(utils/cosign): migrate cosign signature attachment to OCI 1.1 referrers spec

---

server/routing/ROUTING.md
server/routing/cleanup_core_test.go
server/routing/query_matching_test.go
server/routing/routing_local.go
server/routing/routing_remote.go
server/routing/search_simple_test.go

1. Remove the `includeLocators` parameter from `QueryAllNamespaces`
2. Always include all label namespaces (skills, domains, modules, **locators**) in queries
3. Add comprehensive test coverage for `DOMAIN` and `MODULE` query types (previously missing)

fix(dir): locator based remote record search
