agntcy/dir

install/charts/dir/apiserver/values.yaml, install/charts/dir/values.yaml
This PR fixes some helm chart issues.
=> fix: helm chart oci registry endpoint

README.md, USAGE.md, docs/rfc/template.md
Updates the docs and adds RFC templates for feature design and decisions
=> chore: docs updates

api/core/v1alpha1/oasf-validator/skills.go, cli/cmd/build/build.go, e2e/testdata/agent.base.json, e2e/testdata/agent.json
- Created skill fetcher under /api/core/v1alpha1
- Created Validate method and call it in agent builder
- Fixed skill object in test agent data to comply with OASF
=> feat: OASF skills validator

cli/cmd/network/info/info.go, cli/cmd/network/init/init.go, cli/cmd/network/init/options.go, cli/go.mod, e2e/dirctl_test.go
With this PR the `dirctl network init` command will save the generated key to a file on the filesystem.
=> feat(cli): change network commands

e2e/testdata/examples/crewai.agent.json, e2e/testdata/examples/langgraph.agent.json, e2e/testdata/examples/llama-index.agent.json
This PR fixes the test agent jsons to pass skills validation.
=> fix(e2e): test agent skills validation

USAGE.md, cli/build.config.yml, cli/builder/README.md, cli/builder/builder.go, cli/builder/config/config.go, cli/builder/plugins/llmanalyzer/llmanalyzer.go, cli/builder/plugins/pyprojectparser/pyprojectparser.go, cli/builder/plugins/pyprojectparser/pyprojectparser_test.go, cli/builder/plugins/pyprojectparser/testdata/poetry/pyproject.toml, cli/builder/plugins/pyprojectparser/testdata/project/pyproject.toml, cli/builder/plugins/runtime/framework/framework.go, cli/builder/plugins/runtime/language/language.go, cli/builder/plugins/runtime/runtime.go, cli/builder/plugins/runtime/runtime_test.go, cli/go.mod, cli/types/types.go, cli/types/types_test.go, e2e/testdata/agent.base.json, e2e/testdata/build.config.yml, e2e/testdata/pyproject.toml
* Implement new plugin to automatically generate an Agent Base Model from this file which will provide users a valuable starting point for building a Model directly from the source code path.
* The pyproject.toml file in the Agent source code contains essential data required by the Agent Data Model, such as the project name, version, description, and authors. For example:
```
[tool.poetry]
name = "simple"
version = "0.1.0"
description = "simple using crewAI"
authors = ["Your Name [you@example.com](mailto:you@example.com)"]
…
```
=> feat: pyproject parser plugin

cli/cmd/root.go, hub/hub.go
Fixes component naming references
=> chore: cleanup naming refs

client/python/README.md, client/python/example.py
This PR adds an example `README.md` about the usage of the python client SDK.
=> docs: python sdk

.github/workflows/reusable-release.yaml
* windows-amd64 is currently compiled but not uploaded as artifact to release
=> feat: add windows-amd64 release artifact

client/python/README.md
This PR fixes a bug in the python SDK documentation.
=> fix: python sdk

cli/go.mod, client/go.mod, e2e/go.mod, hub/go.mod, server/go.mod, versions.yaml
This PR creates a new release version v0.2.3.
=> release: prepare version v0.2.3

cli/go.mod, client/go.mod, e2e/go.mod, hub/go.mod, server/go.mod, versions.yaml
Prepare release version v0.2.4.
=> release: prepare version v0.2.4

cli/go.mod, client/go.mod, e2e/go.mod, hub/go.mod, server/go.mod, versions.yaml
This PR releases a new version of `v0.2.5`.
=> release: v0.2.5

.github/workflows/demo.yaml, cli/cmd/sign/options.go, cli/cmd/sign/sign.go, cli/cmd/verify/options.go, cli/cmd/verify/verify.go, client/sign.go, client/verify.go
Support non-interactive record signing with Cosign keys and add Sign/Verify to Demo workflow.
Please check https://github.com/paralta/dir/actions/runs/15732926149/job/44338153327 for a simplified demo example.
=> feat: cicd signing

api/core/v1alpha1/oasf-validator/skills.go, api/core/v1alpha1/oasf-validator/skills_test.go
This PR fixes the OASF Validator endpoint to ensure that OASF validation works. Changes in this PR will be part of `v0.2.7` release.
=> fix(backport): update OASF validator endpoint

server/controller/store.go
This PR resolves the digest and size mismatch on the store API by recalculating from the data.
solves https://github.com/agntcy/dir/issues/211 for v0.2.x. this is already solved for the upcoming v0.3.x version
=> fix: resolve digest and size mismatch on Store API

hub/config/config.go, hub/config/constants.go
Remove addition of constant port number to saved hub grpc endpoint in session config file.
=> chore: Remove hub default port

cli/go.mod, client/go.mod, e2e/go.mod, hub/go.mod, server/go.mod, versions.yaml
Signed-off-by: Ramiz Polic <rpolic@cisco.com>
=> release(hub): prepare for v0.2.11

api/go.mod, api/go.sum, cli/go.mod, cli/go.sum, client/go.mod, client/go.sum, e2e/go.mod, e2e/go.sum, server/go.mod, server/go.sum
Bump OASF SDK version to v0.0.5.
=> chore: bump OASF SDK version to v0.0.5

client/verify.go
https://github.com/agntcy/dir/issues/466
Add payload validation in `verifyClientSide()` to ensure signatures are cryptographically bound to the specific record CID.
=> fix(dir/client): verify signature against expected payload

server/go.mod, server/go.sum, server/routing/internal/p2p/constants.go, server/routing/internal/p2p/host.go, server/routing/internal/p2p/server.go
Enables three libp2p features to improve peer connectivity and development experience.
**NAT Traversal:**
- ✅ AutoRelay with dynamic DHT peer source (100% peer reachability)
- ✅ Hole Punching / DCUtR (upgrade relay to direct connections)
- ✅ mDNS local discovery (instant peer discovery on LAN)
=> feat(dir): Enable AutoRelay, Hole Punching, and mDNS for Better Peer Connectivity
